import { useNavigate } from 'react-router-dom'
import { getToken } from '../lib/api'

const FEATURES = [
  {
    icon: '📊',
    title: 'Analytics Dashboard',
    desc: 'Visualise your activity data with beautiful, interactive charts across categories, time, and trends.',
  },
  {
    icon: '✨',
    title: 'AI-Powered Insights',
    desc: 'Get personalised productivity insights generated by an LLM that analyses your patterns and suggests improvements.',
  },
  {
    icon: '🤖',
    title: 'Smart Event Entry',
    desc: 'Type naturally — "Gym every Monday in June 7–8am" — and AI fills in all the details automatically.',
  },
  {
    icon: '📅',
    title: 'Calendar View',
    desc: 'Browse your schedule in a full monthly calendar. Click any day to see, add, edit or delete events.',
  },
  {
    icon: '🔁',
    title: 'Bulk & Series Events',
    desc: 'Create recurring events in one go. Series are tracked together so you can delete one or the whole set.',
  },
  {
    icon: '🔒',
    title: 'Secure by Default',
    desc: 'Every account is protected with mandatory two-factor authentication via any TOTP authenticator app.',
  },
]

const STATS = [
  { value: '6',    label: 'Analytics Views' },
  { value: 'AI',   label: 'Smart Parsing' },
  { value: 'MFA',  label: 'Security Built-in' },
  { value: '∞',    label: 'Events Tracked' },
]

export default function LandingPage() {
  const navigate = useNavigate()
  const isLoggedIn = !!getToken()

  return (
    <div className="landing">
      {/* ── Nav ── */}
      <nav className="landing-nav">
        <div className="landing-nav-logo">
          <div className="logo-mark" style={{ width: 30, height: 30, fontSize: 14 }}>📊</div>
          <span className="landing-nav-brand">EventAnalytics</span>
        </div>
        <div className="landing-nav-actions">
          {isLoggedIn ? (
            <button className="btn btn-primary" onClick={() => navigate('/dashboard')}>
              Go to Dashboard →
            </button>
          ) : (
            <>
              <button className="btn landing-btn-ghost" onClick={() => navigate('/login')}>
                Sign in
              </button>
              <button className="btn btn-primary" onClick={() => navigate('/register')}>
                Get started free
              </button>
            </>
          )}
        </div>
      </nav>

      {/* ── Hero ── */}
      <section className="landing-hero">
        <div className="landing-hero-inner">
          <div className="landing-badge">Personal Activity Intelligence</div>
          <h1 className="landing-headline">
            Track your time.<br />
            <span className="landing-headline-accent">Understand your patterns.</span>
          </h1>
          <p className="landing-sub">
            EventAnalytics turns your daily activities into actionable insights.
            Log events, get AI-generated feedback, and spot trends — all in one place.
          </p>
          <div className="landing-hero-ctas">
            {isLoggedIn ? (
              <button className="btn landing-cta-primary" onClick={() => navigate('/dashboard')}>
                Open Dashboard →
              </button>
            ) : (
              <>
                <button className="btn landing-cta-primary" onClick={() => navigate('/register')}>
                  Start for free
                </button>
                <button className="btn landing-cta-secondary" onClick={() => navigate('/login')}>
                  Sign in
                </button>
              </>
            )}
          </div>
        </div>

        {/* decorative grid */}
        <div className="landing-hero-grid" aria-hidden="true">
          {Array.from({ length: 35 }).map((_, i) => (
            <div key={i} className="landing-hero-cell" />
          ))}
        </div>
      </section>

      {/* ── Stats bar ── */}
      <section className="landing-stats">
        {STATS.map(s => (
          <div key={s.label} className="landing-stat">
            <div className="landing-stat-value">{s.value}</div>
            <div className="landing-stat-label">{s.label}</div>
          </div>
        ))}
      </section>

      {/* ── Features ── */}
      <section className="landing-features">
        <div className="landing-section-label">Features</div>
        <h2 className="landing-section-title">Everything you need to understand your time</h2>
        <div className="landing-features-grid">
          {FEATURES.map(f => (
            <div key={f.title} className="landing-feature-card">
              <div className="landing-feature-icon">{f.icon}</div>
              <div className="landing-feature-title">{f.title}</div>
              <div className="landing-feature-desc">{f.desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── How it works ── */}
      <section className="landing-how">
        <div className="landing-section-label">How it works</div>
        <h2 className="landing-section-title">Up and running in minutes</h2>
        <div className="landing-steps">
          {[
            { n: '01', title: 'Create your account', desc: 'Register with email and set up two-factor authentication for security.' },
            { n: '02', title: 'Log your activities', desc: 'Add events manually, or just describe them in plain text and let AI handle the rest.' },
            { n: '03', title: 'Discover your patterns', desc: 'Explore charts, get AI insights, and use the calendar to stay on top of your schedule.' },
          ].map(s => (
            <div key={s.n} className="landing-step">
              <div className="landing-step-num">{s.n}</div>
              <div className="landing-step-title">{s.title}</div>
              <div className="landing-step-desc">{s.desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── CTA Banner ── */}
      <section className="landing-cta-banner">
        <h2 className="landing-cta-banner-title">Ready to take control of your time?</h2>
        <p className="landing-cta-banner-sub">Free to use. No credit card required.</p>
        <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
          {isLoggedIn ? (
            <button className="btn landing-cta-primary" onClick={() => navigate('/dashboard')}>
              Open Dashboard →
            </button>
          ) : (
            <>
              <button className="btn landing-cta-primary" onClick={() => navigate('/register')}>
                Get started free
              </button>
              <button className="btn landing-cta-secondary" onClick={() => navigate('/login')}>
                Sign in
              </button>
            </>
          )}
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="landing-footer">
        <div className="landing-nav-logo">
          <div className="logo-mark" style={{ width: 26, height: 26, fontSize: 12 }}>📊</div>
          <span className="landing-nav-brand" style={{ fontSize: 13 }}>EventAnalytics</span>
        </div>
        <div className="landing-footer-copy">© {new Date().getFullYear()} EventAnalytics Platform</div>
      </footer>
    </div>
  )
}
