import { useNavigate } from 'react-router-dom'
import { getToken } from '../lib/api'

const FEATURES = [
  {
    title: 'Analytics Dashboard',
    desc: 'Visualise your activity data with interactive charts across categories, time of day, and long-term trends.',
  },
  {
    title: 'AI-Powered Insights',
    desc: 'Productivity insights generated by an LLM that reads your patterns and suggests where your time is going.',
  },
  {
    title: 'Smart Event Entry',
    desc: 'Type naturally — "Gym every Monday in June 7–8am" — and the parser fills in the details for you.',
  },
  {
    title: 'Calendar View',
    desc: 'Browse your schedule in a full monthly calendar. Click any day to see, add, edit or delete events.',
  },
  {
    title: 'Bulk & Series Events',
    desc: 'Create recurring events in one pass. Series stay linked, so you can remove one or the entire set.',
  },
  {
    title: 'Secure by Default',
    desc: 'Every account is protected with mandatory two-factor authentication via any TOTP authenticator app.',
  },
]

const STATS = [
  { value: '6',   label: 'Analytics views' },
  { value: 'AI',  label: 'Natural-language parsing' },
  { value: 'MFA', label: 'Required on every account' },
  { value: '∞',   label: 'Events tracked' },
]

const STEPS = [
  { n: '01', title: 'Create your account', desc: 'Register with an email and set up two-factor authentication.' },
  { n: '02', title: 'Log your activities', desc: 'Add events manually, or describe them in plain text and let the parser handle it.' },
  { n: '03', title: 'Find your patterns', desc: 'Explore the charts, read the AI insights, and keep the calendar in view.' },
]

export default function LandingPage() {
  const navigate = useNavigate()
  const isLoggedIn = !!getToken()

  const ctas = isLoggedIn ? (
    <button className="landing-cta-primary" onClick={() => navigate('/dashboard')}>
      Open dashboard
    </button>
  ) : (
    <>
      <button className="landing-cta-primary" onClick={() => navigate('/register')}>
        Start for free
      </button>
      <button className="landing-cta-secondary" onClick={() => navigate('/login')}>
        Sign in
      </button>
    </>
  )

  return (
    <div className="landing">
      {/* ── Nav ── */}
      <nav className="landing-nav">
        <div className="landing-nav-logo">
          <div className="landing-mark" />
          <span className="landing-nav-brand">EventAnalytics</span>
        </div>
        <div className="landing-nav-actions">
          {isLoggedIn ? (
            <button className="landing-cta-primary" onClick={() => navigate('/dashboard')}>
              Dashboard
            </button>
          ) : (
            <>
              <button className="landing-btn-ghost" onClick={() => navigate('/login')}>
                Sign in
              </button>
              <button className="landing-cta-primary" onClick={() => navigate('/register')}>
                Get started
              </button>
            </>
          )}
        </div>
      </nav>

      {/* ── Hero ── */}
      <section className="landing-hero">
        <div className="landing-hero-inner">
          <span className="landing-badge">Personal activity intelligence</span>
          <h1 className="landing-headline">
            Track your time.<br />
            <span className="landing-headline-accent">Understand your patterns.</span>
          </h1>
          <p className="landing-sub">
            EventAnalytics turns your daily activities into actionable insights.
            Log events, get AI-generated feedback, and spot trends — all in one place.
          </p>
          <div className="landing-hero-ctas">{ctas}</div>
        </div>
      </section>

      {/* ── Stats ── */}
      <section className="landing-stats">
        {STATS.map(s => (
          <div key={s.label} className="landing-stat">
            <div className="landing-stat-value">{s.value}</div>
            <div className="landing-stat-label">{s.label}</div>
          </div>
        ))}
      </section>

      {/* ── Features ── */}
      <section className="landing-features">
        <div className="landing-section-label">Features</div>
        <h2 className="landing-section-title">Everything you need to understand your time</h2>
        <div className="landing-features-grid">
          {FEATURES.map((f, i) => (
            <div key={f.title} className="landing-feature-card">
              <div className="landing-feature-num">{String(i + 1).padStart(2, '0')}</div>
              <div className="landing-feature-title">{f.title}</div>
              <div className="landing-feature-desc">{f.desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── How it works ── */}
      <section className="landing-how">
        <div className="landing-section-label">How it works</div>
        <h2 className="landing-section-title">Up and running in minutes</h2>
        <div className="landing-steps">
          {STEPS.map(s => (
            <div key={s.n} className="landing-step">
              <div className="landing-step-num">{s.n}</div>
              <div className="landing-step-title">{s.title}</div>
              <div className="landing-step-desc">{s.desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="landing-cta-banner">
        <h2 className="landing-cta-banner-title">Ready to take control of your time?</h2>
        <p className="landing-cta-banner-sub">Free to use. No credit card required.</p>
        <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
          {ctas}
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="landing-footer">
        <div className="landing-nav-logo">
          <div className="landing-mark" />
          <span className="landing-nav-brand">EventAnalytics</span>
        </div>
        <div className="landing-footer-copy">© {new Date().getFullYear()}</div>
      </footer>
    </div>
  )
}
